---
- name: Add IP address of all hosts to all hosts
  hosts: all
  become: yes
  become_method: sudo
  any_errors_fatal: true
  tasks:
    # - name: Print variable to debug
    #   ansible.builtin.debug:
    #     msg: "{{hostvars}}"
    # - name: Update hosts file
    #   lineinfile:
    #     dest: /etc/hosts
    #     regexp: '.*{{ hostvars[item].ansible_hostname }}$'
    #     line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
    #     state: present
    #   with_items: "{{ ansible_play_hosts }}"

- name: Install rabbitmq cluster for main app
  hosts: all
  become: yes
  serial: 1
  roles:
    - install-rabbitmq