---
- hosts: rabbitmq
  become: yes
  become_method: sudo
  tasks:
  - name: Create group if not exist
    ansible.builtin.group:
      name: admin
      state: present

  - name: Add the user 'johnd' with specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040
      group: admin