---
- name: Allow Port 22/TCP
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: Using for ssh

- name: Allow Port 4369/TCP
  community.general.ufw:
    rule: allow
    port: '4369'
    proto: tcp
    comment: epmd, a peer discovery service used by RabbitMQ nodes and CLI tools

- name: Allow Port 5671:5672/TCP
  community.general.ufw:
    rule: allow
    port: 5671:5672
    proto: tcp
    comment: used by AMQP 0-9-1 and AMQP 1.0 clients without and with TLS

- name: Allow Port 5551:5552/TCP
  community.general.ufw:
    rule: allow
    port: 5551:5552
    proto: tcp
    comment: used by the RabbitMQ Stream protocol clients without and with TLS

- name: Allow Port 6000:6500/TCP
  community.general.ufw:
    rule: allow
    port: 6000:6500
    proto: tcp
    comment: used by RabbitMQ Stream replication

- name: Allow Port 25672/TCP
  community.general.ufw:
    rule: allow
    port: '25672'
    proto: tcp
    comment: used for inter-node and CLI tools communication (Erlang distribution server port) and is allocated from a dynamic range

- name: Allow Port 35672:35682/TCP
  community.general.ufw:
    rule: allow
    port: 35672:35682
    proto: tcp
    comment: used by CLI tools (Erlang distribution client ports) for communication with nodes and is allocated from a dynamic range

- name: Allow Port 15671:15672/TCP
  community.general.ufw:
    rule: allow
    port: 15671:15672
    proto: tcp
    comment: HTTP API clients, management UI and rabbitmqadmin, without and with TLS (only if the management plugin is enabled)

- name: Allow Port 61613:61614/TCP
  community.general.ufw:
    rule: allow
    port: 61613:61614
    proto: tcp
    comment: STOMP clients without and with TLS (only if the STOMP plugin is enabled)

- name: Allow Port 1883/TCP
  community.general.ufw:
    rule: allow
    port: '1883'
    proto: tcp
    comment: MQTT clients without and with TLS, if the MQTT plugin is enabled

- name: Allow Port 8883/TCP
  community.general.ufw:
    rule: allow
    port: '8883'
    proto: tcp
    comment: MQTT clients without and with TLS, if the MQTT plugin is enabled

- name: Allow Port 15674/TCP
  community.general.ufw:
    rule: allow
    port: '15674'
    proto: tcp
    comment: STOMP-over-WebSockets clients (only if the Web STOMP plugin is enabled)

- name: Allow Port 15675/TCP
  community.general.ufw:
    rule: allow
    port: '15675'
    proto: tcp
    comment: MQTT-over-WebSockets clients (only if the Web MQTT plugin is enabled)

- name: Allow Port 15692/TCP
  community.general.ufw:
    rule: allow
    port: '15692'
    proto: tcp
    comment: Prometheus metrics (only if the Prometheus plugin is enabled)

- name: Enable Firewall
  community.general.ufw:
    state: enabled
  notify: Reload firewall