---
- name: Add or modify nofile/nproc soft/hard limit for wildcard domain
  community.general.pam_limits:
    domain: "*"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_type: 'soft', limit_item: 'nofile', value: 500000 }
    - { limit_type: 'hard', limit_item: 'nofile', value: 500000 }
    - { limit_type: 'soft', limit_item: 'nproc', value: 128000 }
    - { limit_type: 'hard', limit_item: 'nproc', value: 128000 }

- name: Reload settings from all system configuration files
  shell: sysctl --system
