---
# handlers file for install-rabbitmq
- name: Restart rabbitmq-server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes

- name: Reload firewall
  community.general.ufw:
    state: reloaded